[theme]
primaryColor='#6C9BC0'  # radiobuttons etc
backgroundColor="#eee"  # Main color
# secondaryBackgroundColor="#ffe49d"  # sidebar color
secondaryBackgroundColor="#eedda9"  # sidebar color
textColor="#262730"
font="sans serif"